### ISSUE TITLE
Name in use

### ISSUE THREAD

**Issue by ironhaven** [pandaman64/caff#1]
You have claimed the name "caff" on crates.io but don't appear to have any code uploaded. Please respond with your use for this name or can you allow me to use this name on crates.io in the future

**Comment by pandaman64** [comment]
Ah sorry, I meant to build a library but had no time. I'm going to transfer the ownership to you. Can you tell me your username on crates.io?

**Comment by ironhaven** [comment]
I have the same username "ironhaven"

**Comment by ironhaven** [comment]
from https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

All you need to do is

0. cargo login if you have not 
1. pull the git repo
2. do `cargo owner --add ironhaven`
3. Then remove yourself `cargo owner --remove pandaman64`

Thanks for giving me the name

**Comment by pandaman64** [comment]
I sent you an invitation via https://crates.io/crates/caff/owners. Can you confirm?

**Comment by ironhaven** [comment]
I don't see myself as an owner

**Comment by pandaman64** [comment]
Can you check https://crates.io/me/pending-invites?

**Comment by ironhaven** [comment]
The mvp is now posted. Thanks for doing this!
https://crates.io/crates/caff

**Comment by pandaman64** [comment]
I removed myself from owners. Good luck!
